// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecitgydgbqhednaqbkfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjaXRneWRnYnFoZWRuYXFia2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMTQwNzQsImV4cCI6MjA1Mjg5MDA3NH0.j6jUT-1jZ__pTxcnPnGthcwG7bQiSFQNs10JBZO7JRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);